## Univariate Feature selection

In [3]:
# feature extraction with univariate statidtical test (chi-square for classication)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
#load data set
from sklearn.feature_selection import chi2
filename='D:/jupyter notebook workspace/Feture Engineering/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
#for regression: f_regression, mutual_into_regression
#for classification: chi2,f_classif,mutul_into_classif

In [4]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [5]:
array = dataframe.values
X=array[:,0:8]
Y=array[:,8]


In [6]:
test = SelectKBest(score_func=chi2,k=4)
fit=test.fit(X,Y)

In [7]:
set_printoptions(precision=3)
print(fit.scores_)
features=fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [8]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

## Recursive Feature Elimination

In [10]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [11]:
model=LogisticRegression(max_iter=400)
rfe=RFE(model,3)
fit=rfe.fit(X,Y)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [12]:
fit.n_features_

3

In [13]:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [14]:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

## Feature Importance using Decision tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X,Y)

DecisionTreeClassifier()

In [19]:
model.feature_importances_

array([0.072, 0.322, 0.09 , 0.019, 0.03 , 0.217, 0.141, 0.11 ])